name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  is-even:
    runs-on: ubuntu-latest
    steps:
      - name: Is build number even?
        run: '[[ $((${{github.run_number}} & 1)) -eq 0 ]]'
